# Site settings
title:            GOBEP
description:      Guide open BIM pour les échanges par la pratique
keywords:         standards, BIM, openBIM, BuildingSMART, IFC, IDM, MVD, COBie, BCF, bSDD, gbXML, BIMétré
author:           Alexandre Grignon, Nader Boutros
url:              "http://gobep.tech.fr"
repository:       MSBIM/GOBEP

# Versions
version:          v0.1
latest_update:    23/05/2016

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Collections
collections:
  pages: {output: true, permalink: '/:path/'}
  bonnes-pratiques: {output: true, permalink: '/bonnes-pratiques/:path/'}
  
# Assets
sass:
  style: compressed
cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

# Gems (Jekyll plugins)
gems:
  - jekyll-sitemap
  - jekyll-github-metadata

# Pour activer github-metadata : https://github.com/jekyll/github-metadata
# $ JEKYLL_GITHUB_TOKEN=123abc [bundle exec] jekyll serve
